name: Release

on:
    push:
        branches:
            - 'main'
        tags:
            - v*.*.*

permissions:
    contents: write
    packages: write

jobs:
    maven-cleanup:
        name: Maven cleanup
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    sparse-checkout: |
                        gradle
                        build.gradle.kts
                        gradle.properties
                        gradlew
                        gradlew.bat

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: zulu
                    java-version: 17
                    check-latest: true

            -   name: Cleanup
                env:
                    MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                    MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
                run: |
                    ./gradlew closeStagingRepositories

    maven-publish:
        name: Maven publish
        needs: [maven-cleanup]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17
                  check-latest: true

            - name: Publish
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
                  MAVEN_SIGN_KEY: ${{ secrets.MAVEN_SIGN_KEY }}
                  MAVEN_SIGN_PASSWORD: ${{ secrets.MAVEN_SIGN_PASSWORD }}
              run: ./gradlew publishToSonatype -x test

    maven-close:
        name: Maven close
        needs: [maven-publish]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                    gradle
                    build.gradle.kts
                    gradle.properties
                    gradlew
                    gradlew.bat

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17
                  check-latest: true

            - name: Publish
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
              run: ./gradlew findSonatypeStagingRepository closeSonatypeStagingRepository

    maven-release:
        name: Maven release
        needs: [maven-close]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      gradle
                      build.gradle.kts
                      gradle.properties
                      gradlew
                      gradlew.bat

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17
                  check-latest: true

            - name: Release repository
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
              run: ./gradlew findSonatypeStagingRepository releaseSonatypeStagingRepository
