name: Release

on:
    push:
        branches:
            - 'main'
        tags:
            - v*.*.*

permissions:
    contents: write
    packages: write

jobs:
    maven-cleanup:
        name: Maven cleanup
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    sparse-checkout: |
                        gradle
                        build.gradle.kts
                        gradle.properties
                        gradlew
                        gradlew.bat

            -   name: Setup Gradle
                uses: gradle/actions/setup-gradle@v4

            -   name: Setup Java
                uses: actions/setup-java@v4
                with:
                    distribution: zulu
                    java-version: 17
                    check-latest: true

            -   name: Cleanup
                env:
                    MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                    MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
                run: |
                    ./gradlew closeSonatypeStagingRepository -DstagingRepositoryId=io.github.bernatcarbo--5eccc0c4-ded7-496a-82dc-89a86f40e182
                    ./gradlew closeSonatypeStagingRepository -DstagingRepositoryId=io.github.bernatcarbo--6a1f191d-bf7f-477c-ac36-1295f6b45ca3
                    ./gradlew closeSonatypeStagingRepository -DstagingRepositoryId=io.github.bernatcarbo--c5bcf65a-a2f9-47af-8fc8-aca01d600460
                    ./gradlew closeSonatypeStagingRepository -DstagingRepositoryId=io.github.bernatcarbo--ce7460ec-6522-488e-9f77-a376a8a7b005

    maven-publish:
        name: Maven publish
        needs: [maven-cleanup]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17
                  check-latest: true

            - name: Publish
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
                  MAVEN_SIGN_KEY: ${{ secrets.MAVEN_SIGN_KEY }}
                  MAVEN_SIGN_PASSWORD: ${{ secrets.MAVEN_SIGN_PASSWORD }}
              run: ./gradlew publishToSonatype -x test

    maven-close:
        name: Maven close
        needs: [maven-publish]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                    gradle
                    build.gradle.kts
                    gradle.properties
                    gradlew
                    gradlew.bat

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17
                  check-latest: true

            - name: Publish
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
              run: ./gradlew findSonatypeStagingRepository closeSonatypeStagingRepository

    maven-release:
        name: Maven release
        needs: [maven-close]
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  sparse-checkout: |
                      gradle
                      build.gradle.kts
                      gradle.properties
                      gradlew
                      gradlew.bat

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  distribution: zulu
                  java-version: 17
                  check-latest: true

            - name: Release repository
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
              run: ./gradlew findSonatypeStagingRepository releaseSonatypeStagingRepository
