name: Release

on:
    push:
        branches:
            - 'main'
        tags:
            - v*.*.*

permissions:
    contents: write
    packages: write

jobs:
    publish-release:
        runs-on: ubuntu-latest
        timeout-minutes: 25

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'
                  check-latest: true

            - name: Publish to GitHub Packages
              run: ./gradlew publish
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to Maven Central
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}
                  MAVEN_SIGN_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                  MAVEN_SIGN_PASSWORD: ${{ secrets.GPG_PASSPHRASE }}
              run: ./gradlew publish
